server:
  port: 8888
#  http2:
#    enabled: true
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: anhduy12
#    key-password: anhduy12
#    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  main:
    web-application-type: reactive
  application:
    name: GATEWAY

  cloud:
    gateway:
      routes:
        - id: user-info
          uri: lb://USERINFO
          predicates:
            - Path=/api/user/**
          filters:
            - AuthenticationFilter

        - id: security
          uri: lb://SECURITY
          predicates:
            - Path=/api/security/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
jwt:
  jwtSecret: DUY-TC



